{% set name = "openkimmodels" %}
{% set version = "2019.07.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://s3.openkim.org/archives/collection/openkim-models-{{ version|replace('.', '-') }}.txz
  sha256: 50338084ece92ec0fb13b0bbdf357b5d7450e26068ba501f23c315f814befc26

build:
  number: 7
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake <=3.18.2
    - make
    - vim
    - pkg-config
  host:
    - kim-api <=2.2.0
  run:
    - kim-api <=2.2.0

test:
  commands:
    - kim-api-collections-management list

about:
  home: https://openkim.org
  license: CDDL-1.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'All OpenKIM Models compatible with kim-api'

  description: |
    All OpenKIM Models compatible with kim-api.
  doc_url: https://openkim.org/doc/usage/obtaining-models/
  dev_url: https://openkim.org

extra:
  recipe-maintainers:
    - jan-janssen
    - ellio167
